name: Deploy to Firebase Hosting

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v3
        with:
          node-version: '18'

      - run: npm install -g firebase-tools

      - run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > service-account.json

      - run: firebase projects:list --non-interactive
        env:
          GOOGLE_APPLICATION_CREDENTIALS: service-account.json

      - run: firebase deploy --only hosting --project fluff-8790c --non-interactive
        env:
          GOOGLE_APPLICATION_CREDENTIALS: service-account.json
