name: Deploy to Firebase Hosting

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Firebase Tools
        run: npm install -g firebase-tools

      - name: Create Firebase Service Account File
        run: echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" > service-account.json

      - name: Debug: List Firebase Projects
        env:
          GOOGLE_APPLICATION_CREDENTIALS: service-account.json
        run: firebase projects:list --non-interactive

      - name: Deploy to Firebase Hosting
        env:
          GOOGLE_APPLICATION_CREDENTIALS: service-account.json
        run: firebase deploy --only hosting --project fluff-8790c --non-interactive
